definitions:
  models.APIError:
    properties:
      detail:
        type: string
      instance:
        type: string
      status:
        type: integer
      title:
        type: string
      type:
        type: string
    type: object
  models.ConnectRequest:
    properties:
      user_id:
        type: string
      token:
        type: string
    type: object
  models.ConnectResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  models.TokenCreateResponse:
    properties:
      expires_at:
        type: string
      token:
        type: string
    type: object
  models.UserCreateRequest:
    properties:
      email:
        type: string
      inputs_format:
        type: string
      model_type:
        type: string
      outputs_format:
        type: string
      username:
        type: string
    type: object
  models.UserCreateResponse:
    properties:
      user_id:
        type: string
    type: object
  models.UserInfo:
    properties:
      user_id:
        type: string
      created_at:
        type: string
      email:
        type: string
      inputs_format:
        type: string
      model_type:
        type: string
      outputs_format:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /tokens/create:
    post:
      consumes:
        - application/json
      description: create token
      parameters:
        - description: User ID
          in: body
          name: user_id
          required: true
          schema:
            type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/models.TokenCreateResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/models.APIError"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/models.APIError"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/models.APIError"
      summary: create token
      tags:
        - tokens
  /users/:
    get:
      consumes:
        - application/json
      description: get users
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: "#/definitions/models.UserInfo"
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/models.APIError"
      summary: get users
      tags:
        - users
  /users/{id}:
    get:
      consumes:
        - application/json
      description: get user by ID
      parameters:
        - description: User ID
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/models.UserInfo"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/models.APIError"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/models.APIError"
      summary: get user by ID
      tags:
        - users
  /sessions/start:
    post:
      consumes:
        - application/json
      description: start session
      parameters:
        - description: Connect Request
          in: body
          name: ConnectRequest
          required: true
          schema:
            $ref: "#/definitions/models.ConnectRequest"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/models.ConnectResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/models.APIError"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/models.APIError"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/models.APIError"
      summary: start session
      tags:
        - sessions
  /users/create:
    post:
      consumes:
        - application/json
      description: create user
      parameters:
        - description: User Create Request
          in: body
          name: CreateUserRequest
          required: true
          schema:
            $ref: "#/definitions/models.UserCreateRequest"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/models.UserCreateResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/models.APIError"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/models.APIError"
      summary: create user
      tags:
        - users
swagger: "2.0"
