services:
  connection-service:
    container_name: connection-service
    build: .
    env_file: .env
    networks:
      - tpp-network
    ports:
      - "${PORT}:${PORT}"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - .:/app

networks:
  tpp-network:
    external: true
