services:
  connection-service:
    container_name: connection-service
    build: .
    env_file: .env
    networks:
      - tpp-network
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      connections-db:
        condition: service_healthy
    environment:
      - ENVIRONMENT=${ENVIRONMENT}

  connections-db:
    image: postgres:15
    container_name: connections-db
    env_file: .env
    networks:
      - tpp-network
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORDWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - connections-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  connections-db-data:

networks:
  tpp-network:
    external: true
