services:
  auth-gateway:
    container_name: auth-gateway
    build: .
    env_file: .env
    networks:
      - tpp-network
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - .:/app

networks:
  tpp-network:
    external: true
